services:
  app:
    container_name: fixitapp
    image: rusteniojr/fixitapp:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db-fixit;Database=postgres;Username=postgres;Password=postgres"
    depends_on:
      - db-fixit
  
  db-fixit:
    container_name: db-fixit
    image: postgres:17
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}