apiVersion: v1
kind: Service
metadata:
  name: fixitapp-api-service
spec:
  type: NodePort
  selector:
    app: fixitapp-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080 


---
apiVersion: v1
kind: Service
metadata:
  name: fixitapp-postgres
spec:
  type: NodePort
  selector:
    app: fixitapp-postgres
  ports:
  - protocol: TCP
    port: 5435
    targetPort: 5432
    nodePort: 30035